#!/bin/sh

set -e

cd $(dirname $(which "$0"))

if [[ $# -lt 1 ]]; then
    manifests=*.json
else
    manifests="$@"
fi


for manifest in $manifests; do
    flatpak-builder --repo=burniintree --force-clean build-dir "$manifest"
done

flatpak build-update-repo burniintree